---
title: "Trabajo Practico 1"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd('./world-happiness')

db19 <- read.csv('2019.csv', head=TRUE, sep=',', na=NA)
db18 <- read.csv('2018.csv', head=TRUE, sep=',', na=NA)
db17 <- read.csv('2017.csv', head=TRUE, sep=',', na=NA)
db16 <- read.csv('2016.csv', head=TRUE, sep=',', na=NA)
db15 <- read.csv('2015.csv', head=TRUE, sep=',', na=NA)

nuevo<-c('Ranking','Country',"Score",
         'GDP','Social','H&L Expectancy',
         'Freedom', "Generosity",'Corruption')
#verificamos q alinen los nuevos nombres
cbind(colnames(db19),nuevo)

colnames(db19)<-nuevo

db19$Year<-2019
head(db19)

cbind(colnames(db18),nuevo)
colnames(db18)<-nuevo
db18$Year<-2018

viejo<-c("Country","Ranking","Score",
         "hi","lo","GDP",
         "Family","H&L Expectancy","Freedom",
         "Generosity","Corruption","Dystopia")
cbind(colnames(db17),viejo)

colnames(db17)<-viejo
db17$Year<-2017

viejo<-c("Country","Region","Ranking",
         "Score","lo","hi",
         "GDP","Family","H&L Expectancy",
         "Freedom","Corruption","Generosity",
         "Dystopia")
cbind(colnames(db16),viejo)
colnames(db16)<-viejo
db16$Year<-2016
viejo<-c("Country","Region","Ranking",
         "Score","SE","GDP",
         "Family","H&L Expectancy","Freedom",
         "Corruption","Generosity","Dystopia")
cbind(colnames(db15),viejo)

colnames(db15)<-viejo
db15$Year<-2015

columnas.comunes<-colnames(db19)
columnas.comunes<-columnas.comunes[columnas.comunes%in%colnames(db18)]
columnas.comunes<-columnas.comunes[columnas.comunes%in%colnames(db17)]
columnas.comunes<-columnas.comunes[columnas.comunes%in%colnames(db16)]
columnas.comunes<-columnas.comunes[columnas.comunes%in%colnames(db15)]
unificado<-rbind(db19[,columnas.comunes],db18[,columnas.comunes],db17[,columnas.comunes],db16[,columnas.comunes],db15[,columnas.comunes])
```

## Reporte de Felicidad Mundial

Los Datos fueron obtenidos desde <https://www.kaggle.com/unsdsn/world-happiness>.
Se tomaron los datos de los años 2015 a 2019. Se consideraron las siguientes columnas comunes a estos repositorios:
```{r columnas.comunes}
 columnas.comunes
```
## Analisis de Covariables
```{r}
#Forzar Corrupcion a numerico
unificado$Corruption<-as.numeric(as.character(unificado$Corruption))
solo.covariables<-unificado[,c("Score","GDP","H&L Expectancy",
                   "Freedom","Generosity","Corruption")]

str(solo.covariables)
resumen<-apply(solo.covariables,2,function(x){
                     x<-x[!is.na(x)]
                     
                     return(c(
                       max(x),
                       mean(x),
                       median(x),
                       min(x),
                       diff(range(x)),
                       var(x),
                       sd(x),
                       IQR(x),
                       mad(x)
                              ))
                   })
rownames(resumen)<-c("Maximo","Media","Mediana","Minimo","Amplitud","Varianza","Desvio std.","Rango Interc.","Desv. Med. Abs.")
```
```{r echo=FALSE,results='asis'}
library(knitr)
kable(signif(resumen,digits = 3))
```


## Histogramas de las Covariables

Se realizaron los hisotgramas correspondientes a todos las covariables descriptas entre los años 2015 y 2019.
```{r score, echo=FALSE}
hist(unificado$Score,col = "cornflowerblue",lty="blank",
     main = "Histograma Score",xlab = "Score",ylab = "Frecuencia")
abline(v=unificado$Score[unificado$Country=="Argentina"&unificado$Year==2019],
       col="orange",lty="dashed",lwd=2)
legend(2.5,120,legend = c("AR 19"),col=c("Orange"),lwd=c(2),lty = c("dashed"))
#shapiro.test(unificado$Score)
```

```{r GDP, echo=FALSE}
hist(unificado$GDP,col = "cornflowerblue",lty="blank",
     main = "Histograma GDP",xlab = "GDP",ylab = "Frecuencia")
abline(v=unificado$GDP[unificado$Country=="Argentina"&unificado$Year==2019],
       col="orange",lty="dashed",lwd=2)
legend("topright",legend = c("AR 19"),col=c("Orange"),lwd=c(2),lty = c("dashed"))
#shapiro.test(unificado$GDP)
```

```{r HL, echo=FALSE}
hist(unificado$`H&L Expectancy`,col = "cornflowerblue",lty="blank",
     main = "Histograma H & L Expectancy",xlab = "Score",ylab = "Frecuencia")
abline(v=unificado$`H&L Expectancy`[unificado$Country=="Argentina"&unificado$Year==2019],
       col="orange",lty="dashed",lwd=2)
legend("topleft",legend = c("AR 19"),col=c("Orange"),lwd=c(2),lty = c("dashed"))
#shapiro.test(unificado$`H&L Expectancy`)

```

```{r Freedom, echo=FALSE}
hist(unificado$`Freedom`,col = "cornflowerblue",lty="blank",
     main = "Histograma Freedom",xlab = "Score",ylab = "Frecuencia")
abline(v=unificado$`Freedom`[unificado$Country=="Argentina"&unificado$Year==2019],
       col="orange",lty="dashed",lwd=2)
legend("topleft",legend = c("AR 19"),col=c("Orange"),lwd=c(2),lty = c("dashed"))


```

```{r, echo=FALSE}
hist(unificado$`Generosity`,col = "cornflowerblue",lty="blank",
     main = "Histograma Generosity",xlab = "Score",ylab = "Frecuencia")
abline(v=unificado$`Generosity`[unificado$Country=="Argentina"&unificado$Year==2019],
       col="orange",lty="dashed",lwd=2)
legend("topright",legend = c("AR 19"),col=c("Orange"),lwd=c(2),lty = c("dashed"))



```

```{r Corruption,echo=FALSE}
hist(unificado$`Corruption`,col = "cornflowerblue",lty="blank",
     main = "Histograma Corruption",xlab = "Score",ylab = "Frecuencia")
abline(v=unificado$`Corruption`[unificado$Country=="Argentina"&unificado$Year==2019],
       col="orange",lty="dashed",lwd=2)
legend("topright",legend = c("AR 19"),col=c("Orange"),lwd=c(2),lty = c("dashed"))
#shapiro.test(unificado$Corruption)



```

## Analisis de Tendencias


